### ISSUE TITLE
High CPU usage when running mobilenet v2 inference

### ISSUE THREAD

**Issue by fiorano10** [ethz-asl/deeplab_ros#1]
Ubuntu 18.04, ROS melodic, CUDA 10.0, TF 1.14
When running inference using the mobilenetv2_trainaug the CPU usage is unusually high. 10FPS ~ 250%

**Comment by sunt40** [comment]
Hi, when I catkin_make ,the error is as follow:
`CMake Error at deeplab_ros/CMakeLists.txt:4 (find_package):
  By not providing "Findcatkin_simple.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "catkin_simple", but CMake did not find one.

  Could not find a package configuration file provided by "catkin_simple"
  with any of the following names:

    catkin_simpleConfig.cmake
    catkin_simple-config.cmake
`
What should I do?My path is /home/sunt/catkin_ws/src/deeplab_ros.
@fiorano10 @ffurrer @michaelpantic @LBern @HannesSommer

**Comment by fiorano10** [comment]
@sunt40 Delete your `deeplab_ros` repo and then clone [catkin_simple](https://github.com/catkin/catkin_simple) in your `catkin_ws/src/` folder. do a `catkin_build` or `catkin_make`then clone deeplab_ros and it will work

**Comment by fiorano10** [comment]
Also, I fixed the high cpu usage, instead of using skimage use opencv to resize
